services:
    app:
        container_name: app
        image: serversideup/php:8.4-fpm-nginx
        restart: unless-stopped
        env_file:
            - .env
        environment:
            AUTORUN_ENABLED: "true"
            AUTORUN_LARAVEL_MIGRATION: "true"
            AUTORUN_LARAVEL_MIGRATION_FORCE: "true"
            AUTORUN_LARAVEL_MIGRATION_ISOLATION: "true"
            AUTORUN_LARAVEL_MIGRATION_TIMEOUT: "60"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www/html
        networks:
            - app-net
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy

    horizon:
        container_name: horizon
        image: serversideup/php:8.4-fpm-nginx
        env_file:
            - .env
        command: [ "php", "/var/www/html/artisan", "horizon" ]
        volumes:
            - .:/var/www/html
        networks:
            - app-net
        depends_on:
            - redis
            - app

    redis:
        container_name: redis
        image: redis:alpine
        restart: always
        volumes:
            - redis_data:/data
        networks:
            - app-net
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 3s
            retries: 5

    db:
        container_name: postgres
        image: postgres:16-alpine
        restart: always
        ports:
            - "5430:5432"
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: username
            POSTGRES_PASSWORD: password
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - app-net
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U username -d app"]
            interval: 5s
            timeout: 3s
            retries: 10

networks:
    app-net:
        driver: bridge

volumes:
    db_data:
    redis_data:
